sudo: true
language: generic
dist: xenial
os:
- linux
- osx
addons:
  apt:
    sources:
    - sourceline: ppa:ubuntu-x-swat/updates
    - sourceline: ppa:oibaf/graphics-drivers
    update: true
    packages:
    - libglew-dev
    - freeglut3-dev
    - libxi-dev
    - libxmu-dev
    - xorg-dev
    - libgl1-mesa-dev
    - libgl1-mesa-glx
    - libglapi-mesa
    - libgl1-mesa-dri
    - libgbm1
    - libxatracker-dev
    - libxcursor-dev
    - libpulse-dev
    - libxinerama-dev
    - libxrandr-dev
    - libxv-dev
    - libasound2-dev
    - libudev-dev
    - mesa-utils
    - xvfb
    - mesa-common-dev
  homebrew:
    update: true
env:
  global:
  - MESA_GL_VERSION_OVERRIDE=3.3
  - TEST_WITH_XVFB=true
  - LIBGL_ALWAYS_INDIRECT=y
  - DISPLAY=:99
  - ENV_TYPE="conda"
  - ENV_DIR="${HOME}/envs"
  - EXTRA_WHEELS="https://5cf40426d9f06eb7461d-6fe47d9331aba7cd62fc36c7196769e4.ssl.cf2.rackcdn.com"
  - PRE_WHEELS="https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com"
  - EXTRA_PIP_FLAGS="--timeout=60 --find-links=$EXTRA_WHEELS"
  - GH_REF: github.com/fury-gl/fury-website.git
  - secure: h/xMHEc2Uzs5XBzyzEka/U+gj9oC+1k2tW/YXc8YO2Ts+VSb7GnWNpPbOO2NnXB69QwmOLbTVk7To2ShMHpuNhCyS7wHCl45jJTqKyHf9XLFh00Ibp+9+uOG1q2f+8vQ3Yb5yhIQH4N0yzrthPl4VyJhmvKSR6KrbrUPtOaahYPRTc5FLORJ253cXs6qCDL+IWiVnUfI8NXCfxJwU2vDOR9S+WzlAukY/ZDMIiZnBzUkwm3tyWmDO/zrfeeGOUd21jr5svQdq6kIN9ie1258XKB+JW4/5maO4tEjoRkxIBPTX9Acv7TuzUvkGyaQQHde8gOzYCGel2Ou/LOtHzUZRLdC0zTzPlzFC1sSFT44AZKf6t9aZfsHLFF7iIfymWLWOlrcseeJ8ojG25hbENu+BpWY6nj3T8Majs3qDMC+Uox7GSxubede/6aPhTnO5h53+M3LFcZ3QZFsYs0LEddXoKhmwJAFUSMv6BbkoHBA3r+2fF33dCOyJDTZn0WiwmDGx17wfJlTJQbK+2luspQqJRwyTxx7zReVjcdMHhuUkPKEnYx4HgCgKmNHpWbgQvhynji5Y2mwYvaeYlPhZM5qwIjyk80sznazjHZZ4XzBhzx5A8T2vDkfWvz1kH3wwwXMIR+p4LOheKXP5jkHCC2XcjNu6YK8zHkhADut3XhAsYU=
  matrix:
  - PY_VERSION="2.7"
  - PY_VERSION="3.5"
  - PY_VERSION="3.6"
  - PY_VERSION="3.6" OPTIONAL_DEPS=1
  # - PY_VERSION="3.6" ENV_TYPE="pip"
  # - PY_VERSION="3.6" ENV_TYPE="pip" OPTIONAL_DEPS=1
matrix:
  allow_failures:
  - os: osx
  include:
  - os: linux
    env: PY_VERSION="3.6" OPTIONAL_DEPS=1 BUILD_DOCS=1 DEPLOY_DOCS=1
  - os: linux
    env: PY_VERSION="3.6" OPTIONAL_DEPS=1 COVERAGE=1
  # - os: linux
  #   env: PY_VERSION="3.6" ENV_TYPE="pip" OPTIONAL_DEPS=1 USE_PRE=1
install: bash ci/travis/install.sh
script: bash ci/travis/script.sh
after_success:
- if [ "${COVERAGE}" == "1" ]; then coveralls; codecov; fi
- bash ci/travis/deploy_docs.sh
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.ccache"  # https://github.com/travis-ci/travis-ci/issues/5853
